---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpbin
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/TykTechnologies/tyk-istio-demo.git
    targetRevision: HEAD
    path: resources/apis
  destination:
    server: https://kubernetes.default.svc
    namespace: apis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
