---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k6-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: k6-operator
    targetRevision: 3.8.0
    helm:
      parameters:
        - name: namespace.create
          value: "false"
        - name: authProxy.enabled
          value: "false"
  destination:
    server: https://kubernetes.default.svc
    namespace: k6
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k6-configmap
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/TykTechnologies/tyk-istio-demo.git
    targetRevision: HEAD
    path: resources/k6
  destination:
    server: https://kubernetes.default.svc
    namespace: k6
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true