---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://helm.tyk.io/public/helm/charts
    chart: simple-redis
    targetRevision: v0.1.1
    helm:
      releaseName: tyk-redis
  destination:
    server: https://kubernetes.default.svc
    namespace: tyk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tyk-postgres
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: v13.2.3
    helm:
      releaseName: tyk-postgres
      values: |
        auth:
          database: storage
          postgresPassword: topsecretpassword

  destination:
    server: https://kubernetes.default.svc
    namespace: tyk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tyk
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://helm.tyk.io/public/helm/charts
    chart: tyk-pro
    targetRevision: v0.14.1
    helm:
      releaseName: tyk-stack
      values: |
        redis:
          addrs:
          - redis.tyk.svc:6379
        backend: postgres
        postgres: 
          host: tyk-postgres-postgresql.tyk.svc
          port: 5432
          password: topsecretpassword
          database: storage
          sslmode: disable
        dash:
          license: license
          adminUser:
            email: default@example.com
            password: topsecretpassword
          image:
            tag: v5.2
          extraEnvs:
          - name: TYK_DB_ENABLEDELETEKEYBYHASH
            value: "true"
          - name: TYK_DB_ENABLEUPDATEKEYBYHASH
            value: "true"
          - name: TYK_DB_ENABLEHASHEDKEYSLISTING
            value: "true"
        gateway:
          image:
            tage: v5.2
          extraEnvs:
          - name: TYK_GW_POLICIES_ALLOWEXPLICITPOLICYID
            value: "true"
          - name: TYK_GW_ENABLEHASHEDKEYSLISTING
            value: "true"
        pump:
          image:
            repository: tykio/tyk-pump-docker-pub
            tag: v1.8
  destination:
    server: https://kubernetes.default.svc
    namespace: tyk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
